version: '2'
services:

  # The Application
  app:
    image: itkmitl/tcas
    working_dir: /var/www
    env_file: '.env.prod'
    volumes:
      - /var/www/storage
      - "static:/var/www/public"
    environment:
      - "REDIS_HOST=cache"
    restart: always
    

  # The Web Server
  web:
    image: itkmitl/tcas-web
    volumes:
      - "static:/var/www/public"
    ports:
      - 80:80
      - 443:443
    restart: always
  
  cache:
    image: redis:3.2.11-alpine
    restart: always
volumes:
  static:
